on:
  push:
    branches:
      - main

name: Container_Workflow_Dev

jobs:

  build-and-deploy:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
      
    - name: dotnet build
      run: |
        dotnet restore
        dotnet build --configuration Release
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR }}.azurecr.io/backend:${{ github.sha }} -f ./GitHubActions/Dockerfile
        docker push ${{ secrets.ACR }}.azurecr.io/backend:${{ github.sha }}  
        
#     - name: Set Web App ACR authentication
#       uses: Azure/appservice-settings@v1
#       with:
#        app-name: 'app-mail-dqs-dev'
#        app-settings-json: |
#          [
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
#                  "value": "${{ secrets.REGISTRY_PASSWORD }}",
#                  "slotSetting": false
#              },
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_URL",
#                  "value": "https://${{ secrets.ACR }}.azurecr.io",
#                  "slotSetting": false
#              },
#              {
#                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
#                  "value": "${{ secrets.REGISTRY_USERNAME  }}",
#                  "slotSetting": false
#              }
#          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-ui-dqs-dev'
        images: '${{ secrets.ACR }}.azurecr.io/backend:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
